### ISSUE TITLE
Posts not being filtered.

### ISSUE THREAD

**Issue by egel557** [sk22/megalodon#114]
Posts are showing up even though they shouldn't because of my filters. I've checked and they're filtered properly on the web app and on Tusky so I definitely have it set up properly.

**Comment by sk22** [comment]
generally, both megalodon and the official app just load the home timeline from mastodon, which should automatically exclude filtered posts. i'm assuming that maybe the filter does work correctly, but posts that were already loaded before the filters were set up, aren't filtered (because filtering works server-side, and the app just shows whatever the server throws at it). can you check whether this issue also occurs in the upstream, official app?

**Comment by egel557** [comment]
My filters have already been set up for days, but the posts are new. I just tested this now by making a new account and making posts containing my filtered keyword with different visibility settings ("public", "followers only", and "mentioned people only"). I checked my home, local, and federated timelines, they were properly filtered on the web app and Tusky but not on Megalodon. 

Everything I tested seem to be the same for Megalodon and the main app.

**Comment by sk22** [comment]
just checked, you're right. weird. i fully expected the mastodon server to be responsible for filtering out posts (at least the ones marked with "hide completely"), seems not to be the case. it's definitely something that should be (and i think they also will want to do that) fixed upstream - so i don't really want to implement what hopefully gets added in the official app soon anyway

**Comment by sk22** [comment]
maybe i can figure out something for the time being, though!

**Comment by sk22** [comment]
apparently it's already a work-in-progress: the official app's dev commented his comment from a week ago with "TODO support 4.0 filtering": https://github.com/mastodon/mastodon-android/commit/187693883c02388c3a777dea3a6e7e6f0dbd5e3b

**Comment by sk22** [comment]
also, gargron said it's easier in 4.0 in the corresponsing upstream issue: #94 - so i hope it'll be fixed soon

**Comment by sk22** [comment]
Okay, so, this issue probably occurred because the filters only got refreshed once every hour. Now, they get refreshed with every app restart. At least in my testing this appeared to have worked – although the settings and Mastodon 4 features aren't fully respected yet (filtering doesn't happen at all in notifications, for example). But – I won't implement that, it's something that I expect to come from upstream. (If that's not happening for months to come, I might try implementing this on my own, but I don't really want it to come this far.)
