### ISSUE TITLE
Mark notifications as read and add delete button.

### ISSUE THREAD

**Issue by leachimus** [sk22/megalodon#156]
Please add a button to mark the notifications as read and also delete them.

**Comment by sk22** [comment]
There's already a delete function in the settings.
Notifications should be marked as read automatically (as implemented in the official app), even if I've found that to be not 100% reliable.
I could add a button to mark all as read, but since read/unread isn't displayed in the app anyway, such a button wouldn't make any sense, at least not in this context.

**Comment by leachimus** [comment]
Du hast mich nicht verstanden. Es geht mir im die Benachrichtigungen, die man beim herunterziehen sieht. Hier ist es so, dass immer nur die neuste angezeigt wird. Findet jemand einer meiner Beiträge gut, erscheint das bis zur nächsten Benachrichtigung, dann wird der "Stern* überschreiten.

Kannst du mir jetzt folgen?
