### ISSUE TITLE
Digital accessibility: Update notification link contrast

### ISSUE THREAD

**Issue by neurer** [sk22/megalodon#169]
**Describe the bug**
The tremendously helpful update function displays a notification when a new release is available. But depending on the selected color theme _the link_ in that notification does not have enough contrast to be readable. With adaptive brightness and night light turned on it's not readable at all.

**Screenshots and screen recordings**

![github-issue-190837](https://user-images.githubusercontent.com/6098965/208312789-aa43eddf-e763-4d14-b6b1-83d9882438d4.png)

**Version**
Megalodon version: v1.1.5+fork.61

**Comment by sk22** [comment]
that's actually kind of funny to me because the theme you're using is the original mastodon for android color theme - and i didn't change anything about the update notification (the official has this too if you download it from github).
the official app has some more accessibility issues (also when it comes to its color theme), but i'll see what i can do about this particular issue!
