### ISSUE TITLE
Translate function broken

### ISSUE THREAD

**Issue by sk22** [sk22/megalodon#172]

**Comment by neilideal** [comment]
**The "translate" button is not always displayed in the feed. **
I do not know on what principle it works, so I can not tell you how to reproduce. That's why I'm writing in the comments for now, rather than making out the bug. This problem is on mastodon.social, which is why it is not a duplicate for closed #213.
Megalodon Version: Megalodon v.1.1.5+fork 66 (66)
**Post with translate button in feed and in post view:**
![Screenshot_20230117-003000.png](https://user-images.githubusercontent.com/62957728/212769534-c04c2380-5692-4ab7-9f55-84b1130117b1.png)
![Screenshot_20230117-003020.png](https://user-images.githubusercontent.com/62957728/212769644-6f6eb382-da5d-4ea5-bbe3-6e3269b19217.png)
**Post without translate button in feed and in post view:**
![Screenshot_20230117-003011.png](https://user-images.githubusercontent.com/62957728/212769711-15c27a00-d326-4be6-a1c4-ff085d97b9d9.png)
![Screenshot_20230117-003014_Megalodon.png](https://user-images.githubusercontent.com/62957728/212769722-86d1b6ec-88c5-4eaa-ad2b-5410b8deacb5.png)

**Comment by neilideal** [comment]
**The "translate" button is not always displayed in the feed. **
I do not know on what principle it works, so I can not tell you how to reproduce. That's why I'm writing in the comments for now, rather than making out the bug. This problem is on mastodon.social, which is why it is not a duplicate for closed #213.
Megalodon Version: Megalodon v.1.1.5+fork 66 (66)
**Post with translate button in feed and in post view:**
![Screenshot_20230117-003000.png](https://user-images.githubusercontent.com/62957728/212769534-c04c2380-5692-4ab7-9f55-84b1130117b1.png)
![Screenshot_20230117-003020.png](https://user-images.githubusercontent.com/62957728/212769644-6f6eb382-da5d-4ea5-bbe3-6e3269b19217.png)
**Post without translate button in feed and in post view:**
![Screenshot_20230117-003011.png](https://user-images.githubusercontent.com/62957728/212769711-15c27a00-d326-4be6-a1c4-ff085d97b9d9.png)
![Screenshot_20230117-003014_Megalodon.png](https://user-images.githubusercontent.com/62957728/212769722-86d1b6ec-88c5-4eaa-ad2b-5410b8deacb5.png)

**Comment by sk22** [comment]
it should be equivalent to whether the translate button is displayed on mastodon web. generally, it's displayed if the post language (as set by the user, so that might be wrong) ≠ your device's system language, and if the server supports translation at all. if the translate button does appear on web, but not in the app in certain posts, please let me know, otherwise there's nothing i can do

**Comment by neilideal** [comment]
There is no "translate" button on the site for that publication, either. It turns out that the problem is not on megalodon's side
