### ISSUE TITLE
Language selector with abbreviated language name

### ISSUE THREAD

**Issue by edxkl** [sk22/megalodon#216]

**Comment by FineFindus** [comment]
>abbreviated language name

I would look into implementing it, but what exactly is meant by this? The `ISO 639-1 codes`? Or something else?

**Comment by edxkl** [comment]
> > abbreviated language name
> 
> I would look into implementing it, but what exactly is meant by this? The `ISO 639-1 codes`? Or something else?

Just like on Mastodon Web the name of the languages will only have two letters, like this:

`EN` for English, `PT` for Portuguese, `ES` for Spanish, `DE` for German...

**Comment by sk22** [comment]
so uh; why and where would you want the abbreviated name to be displayed? i don't really see an advantage.
implementing it would be easy; the language code is contained in mastodon's name listing anyway

**Comment by FineFindus** [comment]
After implementing this, I actually agree, that it has no current advantages, since it just displays the same information, but shortened (might be useful for very short phones?).
![Proof of concept](https://user-images.githubusercontent.com/63370021/212564775-e38feb7e-9990-4d14-bba5-d36dc01208d7.png)

Possible uses of this could be to:
- free space in the action bar, for future features
- move the language button to the bottom bar, making it easier to reach

But I think both are currently not needed.

**Comment by sk22** [comment]
might reopen if there's a good reason to use the abbreviated name, but i don't see one at the moment, so - closing for now
