### ISSUE TITLE
Separate options for CWs and sensitive media

### ISSUE THREAD

**Issue by benstockil** [sk22/megalodon#233]
**Is your feature request related to a problem? Please describe.**

I'd like to set CWs to reveal automatically, but keep sensitive media hidden (e.g. NSFW images on public TLs)

**Describe the solution you'd like**

The web app has an option to decide when media should be shown / hidden; something similar to this would be good.

![Screenshot_20230101-003554_1](https://user-images.githubusercontent.com/38838553/210158257-35079cd4-f963-4114-abe8-d3024a02b7b6.png)

Thank you so much for your work on Megalodon ❤️

**Comment by sk22** [comment]
as by the looks of upstream development, the redesign will contain slightly altered behavior of how CWs and images are handled (CWs will be toggled by clicking the CW header instead of an eye icon, and images are hidden behind the CW and are revealed by clicking the image after revealing the CW), so i'll wait for the upstream changes to be finished before implementing this. pinned it so i don't forget about it
