### ISSUE TITLE
Respect text scaling

### ISSUE THREAD

**Issue by sk22** [sk22/megalodon#244]
use sp instead of dp

**Comment by neilideal** [comment]
I decided to open Megalodon on my Samsung Galaxy Note 5. Because of my vision problems, I use a text size of 130% of normal. As far as I remember, Megalodon has a text scaling feature, and there is a problem with it in some titles. You can see it better in the screenshots.
I did a comparison without and with in Mastodon and Megalodon:
**With text scaling 130%**
![With_text_scaling_130](https://user-images.githubusercontent.com/62957728/212466325-518d4293-3184-48e1-9e78-02c2de3e474b.png)
**Without text scaling 130%**
![Without_text_scaling_130](https://user-images.githubusercontent.com/62957728/212466339-3f7d0de0-6fcc-42bd-8603-79169dc012ec.png)

**Comment by neilideal** [comment]
I was able to repeat the same thing on the Redmi Note 10
1. Mastodon with text scaling 
![Screenshot_20230114-130211.png](https://user-images.githubusercontent.com/62957728/212466688-47004514-b1c8-419b-9e0f-afc229186fbe.png)
2. Megalodon with text scaling
![Screenshot_20230114-130157.png](https://user-images.githubusercontent.com/62957728/212466703-2f8e898a-2288-414f-8a18-19001ac417e3.png)

**Comment by sk22** [comment]
makes total sense that that happens; many of the UI elements have a fixed height that just cuts the text off. seems like i missed that while testing the scaling. will fix that, thanks!
