### ISSUE TITLE
App crashes when you are writing a post, select text and cut it

### ISSUE THREAD

**Issue by brennomachado** [sk22/megalodon#270]
**Description**
App crashes when you are writing a post (toot) and its end this a emoji shortcut, select part of the text and click on que option "cut" on text selection popup menu.

**To Reproduce**
1. Open the app and go to button to write to a post (toot)
2. Write or paste a text like "Lorem ipsum dolor sit amet, consectetur adipiscing elit. :test:", without the quotation marks
3. Select que text "consectetur adipiscing elit. :test:" and click on "cut" on the text selection popup menu
4. The apps crashs

**Screenshots and screen recordings** 
Video on [this post](https://bantu.social/@brenno/109666564608304914).
Screenshot:
<img height="300" src="https://bagulhos.bantu.social/media_attachments/files/109/666/537/032/730/039/original/7fc3f511e7563e40.jpg">

**Version**
Megalodon version: e.g. v1.1.5+fork.66

**Comment by sk22** [comment]
i've seen this bug recently myself, but i haven't looked into it yet. was able to reproduce it thanks to this report, and i think it's related to special entities like `:custom_emojis:` or `#hashtags` being in the selected text.
now i was also easily able to reproduce this in the upstream app - would be cool if you provided info on that too, as the bug report template suggests, but at least we know now.
since this is a something that crashes the app, i assume upstream will want to have this fixed too, so i'll create an issue there
