### ISSUE TITLE
A completely blank screen with no recent searches looks bad

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#305]
**Is your feature request related to a problem? Please describe.**
A completely blank screen with no recent search queries looks miserable. The thought came to me when I got the closing notice for #188.

**Describe the solution you'd like**
I spent a long time trying to figure out how to solve this problem and was leaning towards an implementation where there would be a mascot (which would still need to be created) of the application with a short text describing the lack of recent searches. But I couldn't find such examples and decided to look for something.

**Describe alternatives you've considered**
I ended up finding an example where this situation is played out purely in text in the middle of the screen. This example is the GitHub mobile app.

**Additional context**
![github_no_recent_search](https://user-images.githubusercontent.com/62957728/212763051-7154aa1e-9828-4db6-a1cc-924117d296c7.png)

**Comment by sk22** [comment]
as you might or might not have seen - i actually introduced a new string in that commit because a blank screen looks bad. it just says "Type something to start searching", but i think it'll do - at least i'm not motivated to put a lot of effort into that.
i would, however, love to display the "advanced search format" (with content adjacent to the mastodon web ui) help text at some point, but that's for another day :')

**Comment by sk22** [comment]
in that case - closing this for now
