### ISSUE TITLE
Pixel: Copy post URL from recent apps

### ISSUE THREAD

**Issue by justaweirdvivi** [sk22/megalodon#475]
**Is your feature request related to a problem? Please describe.**
No, it isn't - however, I requested it because Moshidon implemented it already iirc.

**Describe the solution you'd like**
It's either an Android-native or Pixel feature (I'm not sure about it, to be honest), where you can easily copy text and images from what's displayed, but also (if the app provides an URL of some kind) links from the app switcher UI. It would be nice if it were possible to copy the link to that toot you currently have opened up by entering the app switcher for a short while, while (to name one example) you're about to switch to another app anyways but want to grab that toot's link before leaving.

**Describe alternatives you've considered**
The current alternative is already implemented, which is just opening the 3-dot-menu of the selected toot, and tapping on "Copy link". My suggestion would just be another way to do the same thing, and frankly, just a "nice to have", not a "must have".

**Additional context**
Here's an example (as to how it'd work and look) from the YouTube app in the app switcher: (I didn't have a better example on hand rn, I'm sorry)
![A screenshot of the app switcher, with YouTube in the focus, playing Never Gonna Give You Up. I tapped on that link button in YouTube's app preview (positioned at the top right of it) and then it opened an UI in the app switcher where I could copy and share the YouTube video link easily.](https://user-images.githubusercontent.com/45924578/226713338-43222364-a45f-49dc-a88b-761d9601d79d.png)

**Comment by justaweirdvivi** [comment]
Okay, I was slightly off about Moshidon already having this feature - It is "only" about to come in the stable version soon. (source: https://floss.social/@FineFindus/110039355827594084)

**Comment by sk22** [comment]
well, so, i took a look at @finefindus' commits (https://github.com/LucasGGamerM/moshidon/pull/120/commits), tried to merge them over and came to the conclusion that it'd probably be too painful to do. the pull request builds upon previous features of moshidon, so i'd first have to find out what to remove and what to rewrite and i, especially given that i can't even test this, decided not to keep trying. it'd be cool if we could just upstream (with megalodon being upstream in this case) moshidon features like this one, but often it's just easier (not being a git wizard myself) to rewrite them instead instead of cherry-picking commits :/

however, i feel like upstreaming moshidon features to megalodon might hardly even be possible at this point, given that the "[1508 commits that moshidon is ahead of megalodon](https://github.com/LucasGGamerM/moshidon/compare/sk22:megalodon:main...master)" actually contains many megalodon commits, but cherry-picked over to moshidon. (i personally use "git merge upstream/master" to keep megalodon up-to-date with upstream mastodon for android) - cc @LucasGGamerM

**Comment by LucasGGamerM** [comment]
I actually stopped cherrypicking your commits about 2 months ago, but the number is still massive

**Comment by FineFindus** [comment]
> especially given that i can't even test this

You can test this using the default android studio emulator, even though it is a pixel exclusive feature, which is how I was able to test it.

The reason you cannot simply merge my commits is that in commit d37a2b9db7e28e9924616cff4438259653483a42, which implements the URLs for timelines, it also adds them for CustomLocalTimelines, a moshidon feature. Other than this one change, everything should be compatible with this repo (aside from the horrible code quality of it :)).

> it'd be cool if we could just upstream (with megalodon being upstream in this case) moshidon features

I'm not sure which features exactly you would like to merge, maybe we should work together to upstream some of the changes / make it easier to upstream them.

**Comment by LucasGGamerM** [comment]
Yup, you should also enter our [room](https://matrix.to/#/#moshidon:matrix.org) on matrix so we can better discuss things like this and have an overall smoother interaction. If you may, you can also message me on Mastodon to sort things out!
