### ISSUE TITLE
Go back home

### ISSUE THREAD

**Issue by d4f5409d** [sk22/megalodon#712]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When we are on another timeline for example local or federated, we should be able to go back to the home timeline with a double press of the home icon at the bottom, since single press is going up.

**Describe alternatives you've considered**
If applicable: a clear and concise description of any alternative solutions or features you've considered.
[-]

**Additional context**
[-]

**Comment by sk22** [comment]
having one button do different things when in different states (i.e., scrolling up vs going to a different timeline) isn't exactly user-friendly and can lead to people mistakenly switching timelines when they accidentally pressed the home button twice instead of once.
to go back to the home timeline, you can already press the back button when on any other timeline.
