### ISSUE TITLE
The current profile header is cutting hover

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#726]
**Is your feature request related to a problem? Please describe.**
The current profile header is cutting hover. And I don't think that's good. In the older version we have something like shadow as a background for buttons with max width fill. But what if we use this style? In my opinion, it will make your design better and stop cutting hovers. 

**Describe the solution you'd like**
What do you think about using this (first image) style for the account and user pages instead of this (second image)?

**Describe alternatives you've considered**
You can see something like this on Twitter

**Additional context**
Concept:
![newProfile](https://github.com/sk22/megalodon/assets/62957728/1a59397b-defa-413e-af44-31227274a858)

Current state:
![oldProfile](https://github.com/sk22/megalodon/assets/62957728/29872d81-cdd7-43e8-9034-9e73de5e2789)

**Comment by sk22** [comment]
what does "cutting hover" mean?
anyway, i'm keeping the new design (from upstream) since it (afaik) matches the mastodon header aspect ratio 3:1 (as it's displayed basically everywhere else, also see https://docs.joinmastodon.org/user/profile/#header). it's only cutting something if your header is in another aspect ratio.
i agree that the transparent toolbar looks kinda better, but it also makes it hard to have the 3:1 header image fit without making the whole thing look crammed (with overlapping avatar and action buttons).

**Comment by neilideal** [comment]
![Screenshot_20230719-080908.png](https://github.com/sk22/megalodon/assets/62957728/3824ab22-38a1-48f7-afc4-c01ba16b3a20)
I have Moshidon on my phone too. Here as it was in the previous version. My idea was very inspired by this style. Did something change in the documentation, because I don't think this is 3:1? And in my opinion it cuts less space of hover

**Comment by sk22** [comment]
it's 3:1 on mastodon web, so any header images that are optimized for mastodon are in that aspect ratio. mastodon for android previously didn't follow this, but now does, and it makes more sense imo, as otherwise, proper 3:1 headers would be cut off

**Comment by neilideal** [comment]
What if ...
![Screenshot_20230727-233520.png](https://github.com/sk22/megalodon/assets/62957728/a25ce1a5-960b-4109-bc07-7c89a4f10857)

![Screenshot_20230727-233545.png](https://github.com/sk22/megalodon/assets/62957728/ee02e199-3e0c-4835-91e6-9345f303270c)
