### ISSUE TITLE
Add a color picker

### ISSUE THREAD

**Issue by LucasGGamerM** [sk22/megalodon#73]
The main color is pink, I much prefer the original mastodon purple. Can you add a global color picker for the app?

**Comment by KibSquib48** [comment]
In addition to a manual color picker, could there also be an option to follow the Material You dynamic color scheme?

**Comment by sk22** [comment]
hi! so, no, i can't add a global color picker to the app. i don't know how and this feature isn't important enough to me to be working on it.
i also think a color picker might be pretty complicated, because there's [quite a few (10!) primary/accent colors variations listed in `colors.xml`](https://github.com/sk22/megalodon/blob/e7dc5030d5ab80e4177e24978626457389df6336/mastodon/src/main/res/values/colors.xml#L22-L32) – from lightest to darkest. a color picker would have to dynamically generate those values on the basis of your picked color. when changing the purple colors to pink ones, i also tried scripting it to make my life easier, and i didn't really find a good solution for that either.
apart from that, i wouldn't even know how i can programmatically overwrite values listed in xml files.
if anyone wants to work on it, go ahead – i can't promise to merge it, tho.
closing in favor of #90, which seems much more feasible – but the fact that it's not that important to me, personally, applies there too.
