### ISSUE TITLE
Open by Default links

### ISSUE THREAD

**Issue by Crazyroostereye1** [sk22/megalodon#776]
The Feature I would request is, that when opening links to a Mastodon post that instead of opening the browser it opens Megalodon.

Android has the "open by Default " feature and it seems that the Mastodon app already has support for it for example.

Here is screenshot of the Setting on Megalodon and Mastodon
![Screenshot_20230827-215713](https://github.com/sk22/megalodon/assets/63781667/44f391ca-d2cc-43ee-a3d7-bccab06ab3bc)
![Screenshot_20230827-215657](https://github.com/sk22/megalodon/assets/63781667/0452b873-b0ff-4a10-ad16-57528da42975)

**Comment by sk22** [comment]
the mastodon app can open mastodon.social and mastodon.online links and none more. megalodon doesn't promote the flagship instances (or any other specific list of instances) and therefore won't handle fedi urls for a predefined set of domains. also, there's no agreed-upon fedi url scheme at the moment that could otherwise be used

**Comment by sk22** [comment]
![Screenshot_20230828-023442_Settings](https://github.com/sk22/megalodon/assets/6217438/757296bf-d3f2-4d98-979d-4cdacb9e6e62)

i didn't even know android can display it like this, but this is mastodon's predefined list of supported domains (when clicking on "add link")
