### ISSUE TITLE
Show emoji reactions on timelines setting does not work

### ISSUE THREAD

**Issue by LucasGGamerM** [sk22/megalodon#788]
The Show emoji reactions on timelines setting in the instance category does not equal to any change in app behavior, as there are no flags nor mentions of showEmojiReactionsInLists in any part of the StatusDisplayItem class

**Comment by sk22** [comment]
oops. thanks!

**Comment by sk22** [comment]
well, yes but no. for me, the ideal (and imo should-be-default) behavior is that emoji reactions are shown in timelines - but only if there are emoji reactions. the add button should become visible when opening the post. and there should be a way to disable showing emoji reactions in timeline - which is what the switch currently does.

i don't want the add button to be shown at all times because it takes up a lot of space that's hardly used and conveys no information. i mean yeah, it does add an incentive to add an emoji reaction, but i don't think this alone wins against the visual clutter the button adds.

but yeah, there could be another option to always show the add button. or we could combine the "show emoji reactions in timelines" setting to have the options "always", "hide empty emoji reactions" and "never". maybe that's what i'll do…

btw, the reason i moved @Jacocococo's add button from the post footer (next to reply, boost, fav) to the emoji reactions display item, is that it changed the footer's layout noticably and makes it way more dense - which made it less comfortable for me to look at and use. but other than that, it kind of was the perfect position for that feature...
