### ISSUE TITLE
Firefish Instance Crashes

### ISSUE THREAD

**Issue by KaiserCalm** [sk22/megalodon#818]
**Describe the bug**

Clicking on any video will immediately crash the app, also clicking on certain posts will randomly crash the app and sometimes you can even be stuck in a crash loop.

**To reproduce**

1. Find a post with a video attached. (Video will be 0:00 length)
2. Click on the video.
3. Crash.

OR

1. Find a post.
2. Click on it.
3. Randomly crash.

OR

1. Scroll your feed.
2. Crash.
3. Relaunch the app.
4. Get to the same point.
5. Crash until sufficient posts have been posted to move it further away.

**Does this happen in the official app?**

Does this issue also occur with the respective upstream release?
(Please test using the respective `upstream-xxxxxx.apk` provided in [Releases](https://github.com/sk22/megalodon/releases) or at least using the current Mastodon version from the Play Store)

> No / Yes (I will check later, as I don't have time right now)

> In case it does, please consider filing an [upstream bug report](https://github.com/mastodon/mastodon-android/issues) instead.
> If this bug is seriously impacting your usage or you think I might want to try to fix it for Megalodon, feel free to still create this issue!

**Screenshots and screen recordings**

If applicable, add screenshots (and screen recordings, if possible) to help explain your problem.

**Version**

Megalodon version: v2.0.3+fork.99

**Crash log**

If you know your way around Android development tools, please consider attaching a crash log, if possible.

**Comment by ExperiencersInternational** [comment]
Can't reproduce feed crashing whilst scrolling for a while (can't attach a screenshot, probably something Edge related since I'm experiencing this on a Discourse forum as well).

I also can't reproduce videos making the app crash.

I'm on a slightly older version than you, so you might just need to downgrade.

I have had the app randomly crash on posts but I don't think it's necessarily a Firefish only issue
