### ISSUE TITLE
[Request] For minor change in Search Section.

### ISSUE THREAD

**Issue by ghost** [sk22/megalodon#85]
In search section, please change the position of trending "POSTS" option and move or promote it infront of "LOCAL".
Thank you. ❤️

![IMG_20221122_205935](https://user-images.githubusercontent.com/118822445/203354389-a50a14cd-f465-4cb4-a591-4e792a50dcb6.jpg)

**Comment by acvous** [comment]
I'm completely fine with "LOCAL" and "FEDERATION" sections being on number 2 and 3 but they don't deserve to be on 1'st position for some reasons.
≫ They get updated lot faster because new posts get published after every few seconds.
≫ Most of the posts on those sections are in different languages.
≫ Those sections are big distracting elements; especially when you're on server like fosstodon.org where your main focus is on FOSS or tech but local or federated section does their own independent distracting stuff.

I understand the importance of those sections but 1'st position should be for that section which prefers relevance and quality over quantity of the contents i.e. "POSTS" section.

**Comment by karano-techie** [comment]
In an ideal move , the local and federated timeline should be taken out of the search tab screen altogether and instead put into the bottom navbar menu or on top toggle. It will be more intuitive and will enable users to fully explore mastodon.

**Comment by sk22** [comment]
(i think the "new" home section should resolve this issue)
